sonarqube:
  image: sonarqube
  ports:
    - "9090:9000"
  environment:
    - "VIRTUAL_HOST=sonar.localhost"
    - "VIRTUAL_PORT=9000"
  volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions